### ISSUE TITLE
How to set selected option?

### ISSUE THREAD

**Issue by arisdevx** [Sandalf/vue-bootstrap-select#1]
how to set selected option? v-model="selectedValue" not working

**Comment by Sandalf** [comment]
Could you share a snippet of your code?

**Comment by arisdevx** [comment]
in my code selectedValue is array, for example (laravel):

```
$data = [
   'value' => 2,
   'text' => 'Test',
];
return json_encode($data)
```

but not working when i want to set a selected item.

vue components

```
<div class="form-group required">
                            <label><i>Role</i></label>
                            <v-select
                                class="form-control"
                                v-bind:class="{ 'is-invalid' : error.role }"
                                v-model="form.role"
                                v-bind:options="form.roles"
                            ></v-select>
                            <div class="invalid-feedback">
                                {{ error.role }}
                            </div>
                        </div>
```
```
vue({
	
	.....
	methods: {
		edit(id) {

                ...
                
                axios
                    .get(base_url.concat('/user/', id, '/edit'))
                    .then(function (response) {

                        ...                     

                        this.form.role = response.data.role;

                        ...

                    }.bind(this));
                $('#user-modal').modal('show');
            },
	}
	.....
})
```
the "test" item should be selected, but no one is selected

![bug-kolom-role-1](https://user-images.githubusercontent.com/25075490/52957129-90a6ca80-33c3-11e9-82d1-abfa9ead153c.png)

can you help me asap?

thank you

**Comment by Sandalf** [comment]
When you assign `this.form.role = response.data.role`, does the `response.data.role` object have the same props as in the options array.

Meaning, if `data = [{value: 0, text: 'Test'}]` then your selected value should be `this.form.role = {value: 0, text: 'Test'}` for the select to be able to match the objects.

**Comment by arisdevx** [comment]
below is result of respond data, "Test" id is 2, i have 2 data, 
1. super user with ID 1
2. test with ID 2

![bug-kolom-role-2](https://user-images.githubusercontent.com/25075490/52959148-204e7800-33c8-11e9-8886-c0331919b7b2.png)

**Comment by Sandalf** [comment]
Hmm Its strange, I'll have to set up a laravel project to test it. If you could share a repo where I could test it that'd be great.

**Comment by Sandalf** [comment]
I created a demo where you can play around with the component: https://codesandbox.io/s/ovq821j566
Please ping me If you are able to replicate the same error.
Sorry I haven't had time to test it on laravel, I can probably do it over the weekend.

**Comment by arisdevx** [comment]
thank you for your respond, i found the problem about selected data, when data extracted from axios response and moved to variable (this.form.category) then there's a __ob__ Observer, this is automatically rendered, but no problem in :options

when i fill it manually { value: 0, text: "test" } it's work fine.

below is the data that I got

![bootstra-select-problem](https://user-images.githubusercontent.com/25075490/53573766-c9ebf100-3ba0-11e9-8edb-0c6d96fc7794.png)

Sorry, I just replied to your message because I have a project deadline.

**Comment by arisdevx** [comment]
hmm when i use computed: {} and return {...object} still same problem, not selected data.

**Comment by Sandalf** [comment]
Are you using the computed property correctly?. If you are using a computed prop in a v-model you should be using it with a get and a set like in [the docs](https://vuejs.org/v2/guide/computed.html#Computed-Setter).
