### ISSUE TITLE
How to set the labelTitle

### ISSUE THREAD

**Issue by Ravenna** [Sandalf/vue-bootstrap-select#12]
I am new to Vue but nice component.

I have the data working an all that.  But the default label title still shows.  How can I update the default text?

```<v-select :options="['Member', 'Blog', 'Press', 'Podcast', 'Social Media', 'Internet Search', 'Other']" v-model="pageOne.referred_by" labelTitle="Please Select"/>```

**Comment by Sandalf** [comment]
Using the labelTitle prop as you did should work. You can test it out in  [CodeSandBox](https://codesandbox.io/s/ovq821j566).
Sorry for the late reply

**Comment by Ravenna** [comment]
setting it inline in the component works as you noted: 

`<v-select :options="{{ json_encode(array) }}" v-model="address_country" label-title="Please Select"`
